site_name: Unit Converter Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - About: about.md
  - Getting Started: getting_started.md
  - Reference: reference.md
  - Patch History: patch_history.md
  - License: license.md
